---
title: "Quits and ladders: Does mobility improve outcomes?"
author:
- affiliation: Maynooth University
  name: Ivan Privalko
date: "`r format(Sys.time(), '%B %d, %Y')`"

abstract: "See below"

output:
  word_document: 
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    template: C:/Users/Ivan/Dropbox/plain.template/paper.template/svm-latex-ms.tex

fontfamily: mathpazo
fontsize: 11pt
geometry: margin=3in
keywords: job mobility, career ladders, careers, panel data
spacing: double
bibliography: C:/Users/Ivan/Dropbox/Biblio/bibblio.bib
biblio-style: apsr
---


# Quits and ladders: Does mobility improve outcomes?

July 23, 2018

#### Purpose: 

This article compares internal and external job mobility (quits and promotions) as mechanisms for improving outcomes.

#### Design/methodology/approach: 

We sample the core workforce from the British Household Panel Survey, estimating the effects of quits and promotions using linear fixed-effects methods.  

#### Findings: 

Quits and promotions are distinctly different mechanisms for improving outcomes. External quits improve subjective outcomes, but have no effect on earnings growth. Internal promotions bring earnings growth but have little effect on subjective outcomes. The findings shed light on recent debates over what drives "voluntary" mobility; internal mobility may be driven by "skill acquisition" and efficiency, while external mobility may act as a "sorting mechanism" for conditions and job-fit.

#### Practical implications:

The promises of highly mobile labour markets should be treated with scepticism. The growth of “boundaryless careers” resembles a release valve for poor working conditions and poor job-fit, not an opportunity for growth.

#### Originality/value:

Studies overwhelmingly focus on the effects quitting without explicitly comparing this mobility to promotions. This omission gives an incomplete picture of mobility. Our article shows that quits and promotions have distinctly different consequences for the core workforce, despite both mobility types being labelled “voluntary”. Our analysis helps to understand inequality in earnings and working conditions; core workers who are able to pursue promotion are rewarded objectively; workers who quit for a new employer seek a better job-fit. 

## Introduction

Job mobility is a key mechanism in correcting job-fit and improving earnings. Authors assume that job mobility is of interest to workers because it is driven by the promise of "better" positions elsewhere [@gesthuizen2008mismatching; @le2002job; @kalleberg1979sociology]. This assumption is found in both *job-match* and *job-search* theories, as well as several sociological approaches, widely cited in inequality research [@schmelzer2010consequences; @jovanovic1979job; @sorensen1975structure; @burdett1978theory]. These theories can easily apply to internal promotions as well as external quits. However, empirical studies tend to focus on external mobility, ignoring the effects of promotions [@le2002job; @kalleberg2001satisfied]. This approach offers an incomplete view of mobility and its consequences.

The topic of job mobility is underdeveloped in two ways. First, researchers focus more on the likelihood of mobility than on its consequences [@steenackers2016determinants; @hachen1990three; @hachen1992industrial]. Second, when exploring the consequences of mobility, authors focus on the impact of quits and ignore the impact of promotions [@kronberg2014stay; @kronberg2013stay; @caparros2004gender]. We propose tackling these limitations here.

This article has two aims. First, we compare the effects of internal and external job mobility for the core workforce. Do these mobility types have similar effects and do they carry similar effects for workers? Second, we estimate mobility's impact on subjective and objective outcomes. Comparing and contrasting the effects of quits and promotions on subjective and objective outcomes informs recent debates over the motivations tied to mobility [@mouw2010occupations; @steenackers2016determinants]. Is mobility used to correct the "fit" between an employee and her working conditions, or is it used to correct earnings growth trajectories?

We use the British Household Panel Survey as a representative sample of British workers. Our approach has three strengths. First, we use explicit measures of quits and promotions. A review of the literature shows that authors often sample and operationalise mobile workers in complex ways, some of which may not be valid [@steenackers2016determinants; @kalleberg2001satisfied; @keith1997job; @keith1995wage]. Second, we consider outcomes other than objective pay. By including subjective outcomes, we capture bargains and compromises made by workers who move within or between firms [@latzke2016consequences; @dwyer2004downward; @kalleberg2001satisfied]. Third, we accept recent suggestions and use longitudinal data. In this way we explore the effects of moving positions rather than comparing movers to non-movers [@reichelt2017occupational; @cha2014job; @caparros2004gender].

We offer two findings. First, voluntary mobility is common; quits and promotions are equally likely and are the dominant form of mobility among core workers. Second, internal and external mobility are distinctly different mechanisms with separate effects on outcomes. Internal mobility has the strongest effect on earnings growth, while external mobility has the strongest effect on subjective feelings about work. Crucially, there is no evidence that quits are a substitute for promotions. Instead, British workers may be using external mobility to correct job-fit with a poor employer, as opposed to correcting their earnings growth. In this way, “exit strategies” improve feelings about work; but “loyalty strategies” move a worker's career forward [@hirschman1982exit].

The article is structured as follows; section one summarises the theoretical literature, and introduces a key assumption. Section two summarises the empirical literature and introduces three hypotheses. Section three presents our methodology and approach, while section four presents our results. A brief discussion concludes.

## Theoretical framework

Workers seek the highest level of compensation possible [@sorensen1975structure; @sorensen1978labor]. Voluntary mobility may be one way of achieving this, whether within firms [@gesthuizen2008mismatching; @gesthuizen2009job; @althauser1981firms] or between them [@jovanovic1979job; @burdett1978theory; @keith1997job].

In economics, mobility is understood through two approaches; the *job-search* approach relies on two reservation wages, X and Y (where X<Y). Reservation wage X draws workers into employment, while reservation wage Y draws workers to new positions. Mobility between positions can only occur if workers see financial gain in changing positions; *"An employed worker who is looking for another job will accept any offer received with a wage greater than his current wage"* [@burdett1978theory, p212]. Here, mobility is driven by the promise of wages, which results in *"wage quits"*. The *job-mismatch* approach sees mobility as stemming from a mismatch between a worker's skills and her earnings or conditions [@jovanovic1979job]. Since work is an "experience good", workers take time to evaluate whether their productivity fits with their compensation. If a mismatch exists, workers correct this by pursuing new positions [@sorensen1977outline; @jovanovic1979job]. In this approach too, mobility is (assumedly) the best mechanism to improve earnings or conditions.

In sociology, mobility is also assumed to move workers to "better" jobs. @sorensen1975structure [p460] proposes *“A person may be assumed to shift jobs voluntarily if he can obtain a better job”*; while @hachen1990three [p320] claims *“… in industrial societies, individual attainment… is in large part a function of job changes”*. Since sociologists see rewards as tied to specific positions in a labour market, they often see a change in position as the best mechanism to improve rewards; @sorensen1977structure [p967] suggests *“different people in the same job will obtain the same rewards… the same person will obtain different rewards in different jobs”*. 

Few of the theories above, especially those in sociology, differentiate between quits and promotions explicitly. Most only suggest a relationship between a given position and the next position; the channels which secure the second position are irrelevant. The theories above can easily apply to internal promotions as well as external quits. Despite this, the literature around job mobility focuses heavily on external changes to new employers. As a result, these articles frame quitting as a strategy to improve outcomes. What is more, the few papers which *do* compare internal and external mobility often show how these mobility types lead workers to different outcomes. Further, there is significant evidence that internal mobility yields greater gains for movers than external mobility. We summarise these papers below.

## Voluntary mobility to “better” positions

Mobility’s consequences are understudied. Traditionally, authors have focused more on predicting mobility than its effects [@steenackers2016determinants; @le2002job; @fuller2008job; @pavlopoulos2007benefits; @caparros2004gender]. Conclusions on the effects of mobility differ depending on whether internal promotions are included in the analysis. In order to illustrate the point, we split the literature into two camps; first, studies where authors estimate the impact of external quits alone; second, studies which compare and contrast the effects of internal and external mobility. Studies which estimate the effect of quitting, frame quits as mechanisms for improving most outcomes. Studies which compare and contrast internal and external mobility hold different conclusions. Here, internal mobility is shown to yield higher objective returns, but lower subjective returns. At the very least, internal and external mobility yield different outcomes for workers, which suggests two separate mechanisms for changing outcomes at work [@kalleberg2001satisfied; @gesthuizen2008mismatching; @gesthuizen2009job; @dwyer2004downward]. A brief summary follows.

### External mobility

Authors typically find a positive relationship between external mobility and outcomes. Whether these are subjective [@sallaz2017exit; @kalleberg2001satisfied] or objective [@kronberg2013stay; @kronberg2014stay; @cha2014job; @reichelt2017occupational], workers who quit tend to move to more favourable positions; even when remaining in a similar occupation [@le2002job]. When workers report worse outcomes after mobility, authors frame these as concessions for greater gains in other outcomes. For example, voluntary downward mobility in the US has lead many workers to lower paying positions with greater opportunities or greater work-life balance [@sallaz2017exit; @dwyer2004downward].

In terms of objective pay, workers who quit move to higher paying positions [@kronberg2014stay; @kronberg2013stay; @schmelzer2010consequences; @caparros2004gender]. The effect is also significant over the long-term, and is increasing for some workers [@latzke2016consequences; @kronberg2014stay]. Even when models correct for individual heterogeneity (where certain workers are more likely to quit than others), “economic” quits lead to better paid positions with new employers [@fuller2008job; @keith1995wage]. 

There are some caveats to the effect. First, @latzke2016consequences, @schmelzer2010consequences, and @schmelzer2015varieties find that the premium of quits depends largely on "direct" mobility, where workers avoid unemployment and move from one position directly to another. Successful transitions from one job to another require workers to search for opportunities *on the job*. In other words, the premium tied to changing positions is reliant on *researvation wage Y*, mentioned above. Second, there are significant differences between workers in the mobility-outcomes relationship. The positive effect of quitting may be mitigated by worker characteristics, where men benefit from mobility more than women, and white workers gain more from mobility more than black workers [@kronberg2014stay; @kronberg2013stay]. These differences are not always replicated in subsequent studies, but generally, authors agree that core workers benefit from external mobility more than periphery workers [@caparros2004gender; @cha2014job; @fuller2008job].

In terms of subjective or "soft" outcomes, external mobility also leads to better positions. @sallaz2017exit finds that call centre workers with poor conditions see quitting as a strategy to improve outcomes, even when moving to lower paid positions. Here, workers are motivated to leave “dead-end” jobs and are willing to accept less money for better future opportunities and conditions. @dwyer2004downward too argues that downward wage mobility is an explicit strategy to improve conditions with new employers. In both examples, workers trade pay for better "soft outcomes", a strategy which goes against *job-search* approach, but fits with the *job-matching* approach. @latzke2016consequences show that external quits to a new employer has a significant effect and lasting effect on satisfaction with work. This effect has also remained strong over time. In short, mobility not only has a financial benefit to workers, but is said to have subjective benefits too. 

None of the authors above consider internal mobility or promotions as a means to improve outcomes. As a result, they take a limited view of “voluntary” mobility. Despite a decline in firm tenure and career opportunities [@cappelli1999career; @jacoby1999career], internal careers are the main hope for most workers [@rigotti2014gains]. It is also the *"most desired type of job mobility, because promotions increase status, esteem, responsibilities, and financial rewards"* [@ng2007determinants]. When workers quit a firm, they face an obvious opportunity cost: the chance of promotion. How does this mobility type compare to quits?

One reason for the omission may be related to data. Both @fuller2008job and @keith1995wage sample young workers from the National Longitudinal Survey of Youth, where internal mobility is not measured. Further, this survey splits mobility for family, involuntary, and “other” reasons; where "other" mobility types are operationalised as "economic quits". In Germany too, internal mobility captured by the German Socio-Economic Panel may be flawed [@kattenbach2014quarter]. This lead @kattenbach2014quarter and @schmelzer2010consequences to drop internal mobility from their analysis. In short, finding data on internal promotions and external job quits is a challenge. Despite this, when internal promotions are included into the analysis, significant differences emerge between the two mobility types.

### Internal and external mobility patterns

Studies comparing the consequences of quits and promotions are rare. However, when authors compare and contrast these, three wrinkles typically emerge. First, internal mobility presents stronger and more significant earnings growth than external mobility [@le2002job; @gesthuizen2008mismatching]. Second, external mobility presents stronger and more significant effects on subjective outcomes than internal mobility [@gesthuizen2009job; @gesthuizen2008mismatching]. Lastly, internal mobility is associated with a mix of positive and negative consequences [@lup2017something; @rigotti2014gains]. If workers want to improve outcomes, they may have to consider which outcomes are in need of attention before committing to a mobility type. 

On the first point, mobility within the firm often results in far greater earnings growth than quitting [@le2002job; @gesthuizen2008mismatching; @pavlopoulos2007benefits]. In Sweden @le2002job compare internal and external mobility, controlling for a variety of biases. They find internal promotions have the strongest effect on earnings growth, although external movement also carries a premium. The effect is also “pure”, in that it remains when controlling for occupations. In the Netherlands @gesthuizen2008mismatching report a similar finding; internal promotion has the strongest effect on earnings and socio-economic status. As before, external mobility holds a premium for both outcomes, but this premium is weaker and less significant than the premium tied to internal mobility. One caveat to the effect is that it may rely on a market's institutional setting. @pavlopoulos2007benefits analyse panel data from the UK and Germany. Results from Britain confirm Le Grand and Tahlin's (2006) results, internal mobility has the strongest effect on British workers' earnings. Howeveer, results from Germany are the reverse; external mobility has the strongest effect on German workers' earnings. Generally, when authors compare quits and promotions, it is the latter which rewards objective outcomes best.

Elsewhere authors argue that external mobility has the stronger effect on subjective feelings about work, when compared to internal mobility. In the Netherlands, @gesthuizen2009job finds quits improve several subjective outcomes, while internal mobility has a weak effect on the same outcomes. Moving to a new employer improves workers evaluation of their job fit, their satisfaction with wages, and their satisfaction with hours. @gesthuizen2008mismatching also find that external mobility has the strongest effect on subjective feelings about work using several measures of satisfaction. These papers suggest that subjective feelings about work and the mismatch between a workers expectations and working conditions, drive mobility. It's possible that those who quit are at a lower base than those who take a promotion, however the intervention of quitting has a strong and significant effect for each outcome. 

Lastly, the two sets of findings above make sense when we condier the full effects of promotion. Typically, respondents who experience promotion report both positive and negative changes in outcomes [@lup2017something; @rigotti2014gains]. In the UK @lup2017something finds that women who are promoted often report lower working conditions after the transition, despite seeing minor positive changes in satisfaction with work. In Germany @rigotti2014gains find promotions are associated with both positive and negative outcomes. Here, higher career satisfaction is balanced with increased strain and increased demands. It makes sense that promotions would yield stronger earnings growth while having negative effects on some subjective outcomes. After all, these workers transition to positions with new responsibilities and pressures. These pressures are often greater than the objective rewards and resources given to those who are promoted. Thus internal mobility moves workers to "better" jobs in some outcomes, but leads to compromises in others. 

Mostly, the papers above challenge the idea that mobility is a utilitarian process which brings workers to “better” positions. We draw two conclusions from the review; first, there is a lack of studies which consider the impact of both quits and promotions. Second, there is a lack of studies which use outcomes other than pay. With this in mind, we propose three hypotheses:

##### Hypothesis 1: Internal and external mobility will have significantly different effects on outcomes
##### Hypothesis 2: External mobility will bring greater subjective satisfaction than internal mobility
##### Hypothesis 3: Internal mobility will bring greater earnings growth than external mobility

## Methodology

The general approach of the paper can be summarised as follows. We sample nine rounds of the BHPS covering the pre-crisis period (2000-2008). Using the sample we draw out subjective and objective measures of reward, a number of controls, and a measure of job mobility. We also restrict the sample to a semi-balanced panel, allowing respondents to miss only a single year in the 2000-2008 period. We first estimate the effect of job mobility on subjective outcomes using fixed-effects linear regression. We then compare the estimates for internal and external mobility using an f-test. We carry out the same estimation for objective outcomes, and discuss the results.

### Sample

The British Household Panel Survey is a longitudinal study of UK respondents [@taylor1993british]. The data was collected at the household level between 1991 and 2008, and contains detailed work histories, socio-economic measures, and measures of work reward. It is routinely used to represent the wider British workforce [@pavlopoulos2007benefits], and is particularly useful for studies of job mobility since it operationalises both internal and external mobility types.

The sample used through the article is made up of; observations from respondents missing no more than one wave between 2000 and 2008; observations where respondents are employed at each interview and are not in self-employment, inactivity, or education; and observations where respondents have no missing job history information for a given survey year. The final data shape takes the form of a semi-balanced, person-year file, which ignores households and focuses on individual responses. It is made up of 3,782 respondents and 32,560 person-year observations. Although authors argue that unbalanced panels do not hinder multilevel estimation techniques [@gelman2006data], we use a semi-balanced panel for theoretical reasons, avoiding respondents who are not part of the core workforce, and are prone to periods of unemployment. 

### Variables

This section outlines the variables used in estiamtion. For clarity, we break these down into three cateogries; measures of job mobility, control measures, and outcomes. We discuss each in turn. Two file-sets contain the variables used for estimation, the individual response files “INDRESP”, and the individual job history files “JOBHIST”. Individual response files measure the status of respondents in a given survey year. They contain all outcomes used in estimation and most of the controls. The job history files measure job mobility and changes in job spell for a given year. These take the form of job-spells which are nested in individual responses, rather than observations nested in individuals. For the purpose of this paper, we consider only the most recent spell in a given respondent’s work history file. Brief, earlier, spells (lasting less than a year) represent economic turbulence rather than clear transitions to new positions. As a result, these are not representative of career transitions as they appear in the literature. Further, although previous authors often control for unemployment, this is not the aim of this article, and so these periods are ignored. In short, respondents are permitted brief periods of unemployment when changing positions, although these are relatively rare.

#### Job Mobility

Each job history file contains spell data for the last 12 months of a respondent’s career. Respondents recount each spell of employment, from their most recent, working backwards. Respondents who work in the same job, with the same employer, describe "spell 0" and have only one entry in the job history file. Of those who change spell, it’s possible to discern between internal and external changes (JHSTAT). It is also possible to discern between voluntary and involuntary changes (JHSTPY). Those who list a “promotion” or a move to a “better job” are said to move for voluntary reasons. Those who move due to “dismissal”, “redundancy”, or “temporary contracts” are said to move for involuntary reasons. The purpose of the article is to estimate the effect of voluntary mobility, but is important to control for involuntary events also, which likely have an effect on outcomes [@keith1997job; @sorensen1975structure]. Respondents who change positions for “other” reasons are controlled for in a category marked “other”; these estimates are not relevant to the analysis and are ignored, although they feature in the models. 

#### Outcomes

Previous studies estimating the consequences of mobility typically focus on pay. While we include the measure here (paygu), the literature notes *“jobs may be characterized by the economic, social and psychological rewards they provide incumbents”* [@sorensen1977outline: p967]. With this in mind, focusing on economic consequences alone would offer an incomplete picture of mobility. For this reason, we consider three subjective outcomes, related to pay, hours, and the work itself (jobsat2, jobsat6, and jobsat7). Beyond this, authors routinely show the impact of mobility on working time and working hours. We use weekly working hours as an outcome to test the effect mobility has on working conditions.

#### Controls

Measuring the impact of mobility on outcomes without controls would not give a “true” effect. This is especially true for fixed effects linear estimation which is susceptible to "ommitted variable bias" [@longhi2014practical; @wooldridge2010econometric]. Previous authors cite the importance of controlling for industry and occupation when predicting the effect of mobility [@le2002job]. Others cite the importance of age and the number of children in the home, which are strong predictors of earnings [@cha2014job; @keith1997job; @fuller2008job]. Contract type, and the size of the firm are standard controls for the economic sector [@schmelzer2010consequences; @steenackers2016determinants]. Lastly, the survey year, the country’s unemployment rate, and the rate of economic growth are included in an effort to control for macro changes which may affect wages and subjective evaluations of work [@gesthuizen2009job].

### Estimation

Voluntary mobility, of either type, is not a random event. Part of the reason articles report strong and significant estimates between mobility and outcomes is due to fundamental differences between mobile and immobile workers (individual heterogeneity). Since worker characteristics play a part in deciding who quits and who is promoted, we remove their influence from the estimation process using fixed-effects estimation [@allison2009fixed; @longhi2014practical]. 

The within-transformation, or fixed-effect, removes all unobserved individual heterogeneity from the model’s estimates by subtracting each term from its cluster mean. Wooldridge (2010:p 485) refers to this process as “time demeaning”, claiming *“...any explanatory variable that is constant over time for all [individuals] gets swept away by the fixed effects transformation”*. In this approach, all time invariant measures, both observed and unobserved, are dropped from the estimates. The method is particularly suited to two authors mentioned above. @sorensen1977outline argues that worker resources are fixed from the moment they enter the labour market. Thus, the change in outcomes resulting from mobility is the effect of respondents “closing the gap” between resources and attainment. @jovanovic1979job too sees mobility as stemming from a job-mismatch, and assumes that fixed worker resources have little to do with mobility. Since all of the proposed outcomes are linear, we use linear fixed-effects estimation throughout. 

Two limitations of this method should be noted. First, fixed-effects estimation provides unbiased estimates for mobility. However, the method is inefficient and relies only on variance within clusters, discarding variance between clusters which are “contaminated” by unobserved subject-specific characteristics [@allison2009fixed; @longhi2014practical]. Therefore, fixed effects estimates produce larger standard errors, wider confidence intervals, and larger p-values. For this reason, we treat estimates with p-values of less than 0.1 as statistically significant. Second, fixed effects estimates are susceptible to omitted variable bias. If models omit crucial time-variant variables, other measures which correlate with the effect will produce significant results. However, the models below already consider a wide range of explanations for inequality in outcomes, including changes in the occupation and industry of respondents. On average, the models presented here are more conservative than those of other authors. 

## Results

Table 1 lists the frequency of mobility within the sample. Here, we present the commonality of voluntary mobility before checking the commonality of quits and promotions. The figures are split in three ways; overall, between, and within respondents. Regarding observations alone, most of the UK’s mobility is "voluntary", either to a new employer or to a new position with the same employer (column 1). Thinking of mobility between respondents (column 2), 33% of respondents quit voluntarily at least once during the panel; 30% of respondents took a promotion at least once during the panel. Regarding mobility for the average respondent (column 3), both types of voluntary mobility are more common throughout the 9 wave period than the other mobility types listed. Together, the figures suggest *many British workers move often for voluntary reasons*. We now consider the key question of the analysis, what do workers get from this mobility?

[TABLE 1 HERE]

### Mobility and subjective outcomes

The results of three fixed-effects regression models are listed below. We consider three subjective outcomes; satisfaction with work (model 1), satisfaction with pay (model 2), and satisfaction with hours (model 3). For clarity, we omit the estimates for “other” mobility types, which are controlled for, but are not relevant to our wider argument. Specifically, we are interested in whether quits and promotions have significantly different effects on our outcomes (hypothesis 1) and whether quits have a stronger effect on these outcomes than promotions (hypothesis 2).

[TABLE 2 HERE]

There is a clear distinction between voluntary and involuntary mobility in each model. Voluntary mobility leads workers to subjectively better positions while involuntary mobility has no effect. This is consistent with the *job-matching* approach (Jovavich; Kalleberg and Maouw) and the wider *attainment* approach (Sorensen) discussed above. However, there are also significant differences between quits and promotions in each model. 

Begining with work satisfaction (model 1), an F-test reveals that quits have a stronger effect on the outcome than promotions (F(1, 3723)= 25.54, p >F = 0.000). A similar result emerges for satisfaction with pay (model 2), an F-test shows that quits have a stronger effect on the outcome (F(1, 3723) = 18.21, p > F = 0.000). Lastly, satisfaction with time (model 3) is affected in the same way as the previous outcomes. Those who quit see a larger effect than those who take a promotion (F(1, 3723) = 10.32, p > F= 0.001). In every case respondents who leave an employer find more satisfying positions than respondents who take promotions with the same employer.

Using the findings above, we confirm hypothesis 1; internal and external mobility have a significantly different effect on outcomes. Further, we confirm hypothesis 2; external mobility has a stronger effect on subjective outcomes than internal mobility. Quitting may be driven by job-mismatch instead of attainment as described in the literature. Workers who quit a firm may be less interested in career progress, and more interested in leaving poor conditions and a poor job-fit behind (Jovanovic). The findings above resemble previous studies of mobility on subjective outcomes (Latzke, Gesthuizen; Gesthuizen and dagevos; Kalleberg and Mastekaasa) 

It is worth briefly considering a second explanation. @sorensen1977structure implicitly suggests that working conditions vary less within the firm than between firms, since “opportunity structures” within the firm are smaller. As a result, workers are limited in the extent to which they can improve outcomes with the same employer. If such opportunity structures exist, a set of objective outcomes will respond to mobility in the same way as above; with external mobility yielding strong effects, and internal mobility yielding weaker effects. We keep this idea in mind while revisiting hypothesis 1 and testing hypothesis 3.

### Mobility and objective outcomes

The models in Table 3 are similar to those in Table 2, they estimate the effect of mobility on weekly hours worked (1) and log wages (2). Since mobility has a significant effect on both outcomes, we run the model for wages a second time, controlling for weekly hours worked (model 3). As before, we are interested in whether quits and promotions have significantly different effects on both outcomes (hypothesis 1), and whether promotions have a stronger effect on outcomes than than quits (hypothesis 3).

[TABLE 3 HERE]

The effects of voluntary mobility are less clear than before. Voluntarily changing jobs has an effect on hours and pay, but only under certain conditions. Promotions have the strongest effect on pay without a corresponding effect on hours. Quits have a positive effect on pay, but this is followed by a rise in working hours. While promotions reward workers with higher pay, quits appear to be a bargain over working time. We elaborate on this point below.

Starting with weekly working hours; the estimates for voluntary mobility have mixed effects. Quitting leads workers to positions with longer hours (model 1), and promotions lead workers to positions with fewer hours (the estimate is not significant). Considering gross monthly pay (model 2), both quits and promotions lead to workers to higher paying positions. However, there is no difference between quitting or gaining a promotion in terms of higher pay. Although an increase exists, it is small; workers may need to pursue several new positions over the course of a career before seeing a substantial change in pay. Thinking of both models together, the 1% increase in pay may be tied to longer hours. With this in mind, we re-estimate the effect of mobility on pay, while controlling for weekly working hours (model 3). This eliminates the positive estimate for quitting, but not for promotions. Thus external mobility is tied to bargains over hours for similar rates of pay; while internal mobility is tied to *higher paying positions in themselves*. 

From the estimates above, we confirm hypothesis 1. Internal and external mobility have different effects on outcomes. We also confirm hypothesis 3, internal mobility rewards workers best when outcomes are objective. These findings add further support to our argument that two separate mechanisms influence mobility. Promotions resemble the career progress and earnings growth described by Sorensen, and the reservation wage proposed by Burdett; quits on the other hand appear to be a strategy of gaining more hours.

The estimates in Table 3 resemble those of previous authors who compare internal and external mobility. Gesthuizen and Dagevos, and elsewhere Le Grand and Tahlin both report higher earnings growth from promotions when compared to quits. In the UK, Pavlopoulos too report greater earnings growth from internal mobility when compared to external mobility, although this result is flipped in the results for Germany. Thus, the idea that high inter-firm mobility stems from greater opportunities between firms than within them, does not emerge. 

## Discussion

This article compares the impact of internal and external mobility on worker outcomes. Internal mobility types have largely been ignored in the literature. As a result, studies of job mobility focus extensively on who experiences job quits or job hopping [@gesthuizen2009job; @steenackers2016determinants], and what are the returns to job quits or job hopping [@caparros2004gender; @kronberg2014stay]. This approach has a tendnecy to frame mobile working lives as the result of workers shopping for better opportunities elsewhere [@brown2008economic; @oecd2010oecd]. This view minimises precarity and ignores the fact that internal and traditional, channels for career progression often carry the best rewards for workers. 

We find that internal and external mobility types are distinctly different mechanisms, with different consequences for workers. Internal mobility leads workers to marginally better conditions but significantly higher pay. External mobility leads workers to positions with better conditions without increased pay. Authors often cite the death of internal labour markets and a rise in "boundaryless" career types [@cappelli1999career; @jacoby1999career]; it is important to ask, what do workers get from these new institutional settings? The work above shows that external labour markets are no substitute for the rewards offered by traditional career ladders. Instead, job quits likely stem from a worker's need to correct poor conditions and a poor job-person fit.

As working conditions continue to change, widen, and become individualised, mobility will increase. The British referendum to leave the European Union is already having an impact on working conditions, like the European Working Time Directive. This will likely lead to larger rates of inter-firm mobility as workers try to bargain for greater job fit in a market of increasingly varied outcomes.

The assumption that workers have much to gain from mobile labour markets should be treated with scepticism, since the conclusion assumes the interests of labour and the interests of capital are the same. Instead mobile markets may act as a release valve for poor working conditions, or an alternative to the lack of career ladders which employers avoid constructing. As @sorensen1983processes noted later, *“One may see the considerable amount of inequality in personal attainments found in labor markets... to be created in large organization as deliberate devices to move employee performance from perfunctory to consummate.”* This catch may have spilled into the wider economy, where precarity and mobility are "deliberate devices" to maintain a turning market of poor working conditions. Keeping employees mobile means limiting the commitments and obligations that employers have to their staff; authors may suggest mobility is still a crucial strategy to placing workers into organisations with better conditions and opportunities. We should consider the importance of ensuring such conditions as standard.

## References
