---
title: "Satisfied Movers Revisited"
author:
- affiliation: Maynooth University
  name: Ivan Privalko


abstract: 
output:
  word_document: 

bibliography: C:/Users/Ivan/Dropbox/Biblio/bibblio.bib
biblio-style: apsr
---

### Purpose:

This article compares internal and external job mobility (quits and promotions) as separate mechanisms for improving earnings and job-fit.

### Design/methodology/approach:

We sample the core workforce from the British Household Panel Survey, estimating the effects of quits and promotions on two sets of outcomes. The first are subjective; satisfaction with work, pay, and hours. The second are objective realities about the job; gross monthly pay and weekly working hours. We use linear fixed-effects estimation to control for individual heterogeneity.

### Findings:

Quits and promotions are distinctly different mechanisms for improving earnings and conditions. External quits improve satisfaction with work, pay, and hours but have little effect on earnings growth. Internal promotions bring earnings growth but have little effect on satisfaction outcomes. Our findings shed light what drives “voluntary” mobility; internal mobility may be driven by higher “reservation wages” and career progression, while external mobility may be driven by a poor job-fit.

### Practical implications:

Researchers should treat mobile labour markets with scepticism. The growth of “boundaryless careers” may closer resemble a release-valve for poor working conditions and poor job-fit, and not a wealth of new opportunities for progress or earnings growth.

### Originality/value:

Studies of job mobility overwhelmingly focus on the effects quitting without explicitly comparing this mobility to promotions. This omission gives an incomplete picture of mobility. Including promotions into the discussion helps to understand why workers commit to internal careers and to firm tenure. Our article shows that quits and promotions yield distinctly different outcomes for core workers, despite both mobility types being labelled “voluntary”. Inequality in earnings and working conditions are closely tied to access to the “life-chances” of mobility; those who are able to pursue promotion are rewarded objectively; those who quit for a new employer seek a better job-fit.
Introduction

# Introduction

Researchers assume job mobility is of interest to workers because it leads to “better” positions elsewhere [@gesthuizen2008mismatching; @le2002job; @kalleberg1979sociology]. This assumption exists in both economic (job-match and job-search theories) and sociological (attainment theory) approaches, widely cited in inequality research (Schmelzer 2010; Jovanovic 1979; Aage B Sørensen 1975; Burdett 1978). These theories can easily apply to internal promotions as well as external quits, but empirical work has overwhelmingly focused on quitting, ignoring the effect of promotions (Le Grand and Tåhlin 2002; Kalleberg and Mastekaasa 2001). This approach offers an incomplete view of mobility and its consequences.
We suggest the topic is underdeveloped in two ways. First, researchers have focused more on the likelihood of mobility than on the effects of mobility (Steenackers and Guerry 2016; Hachen Jr 1990; Hachen Jr 1992). Second, when authors explore the effects of mobility, they often ignore the impact of promotions (Kronberg 2014; Kronberg 2013; Caparrós Ruiz, Lucía Navarro Gómez, and Federico Rueda Narváez 2004). We consider these limitations below.
The article has two aims. First, we explicitly compare the effects of internal and external mobility for the economic core. Do quits and promotions have a similar effect on earnings and job-fit? Second, we consider mobility’s effects on subjective and objective outcomes. Comparing and contrasting the effects of quits and promotions on two different sets of outcomes informs recent debates over the motivations tied to mobility (Kalleberg and Mouw 2016; Steenackers and Guerry 2016). Is mobility used to correct the job-fit between an employee and her working conditions, or is it used to maximise earnings growth by letting workers reach a reservation wage?
We use the British Household Panel Survey as a representative sample of British workers. This approach has three strengths, which are relevant to the wider debate. First, we use explicit measures of quits and promotions. A review of the literature shows that authors often sample and operationalise mobile workers in complex ways, some of which may not be valid (Steenackers and Guerry 2016; Kalleberg and Mastekaasa 2001; Keith and McWilliams 1997; Keith and McWilliams 1995). Second, we consider outcomes other than objective pay. By including subjective outcomes, we are able capture changes in job-fit and general satisfaction (Latzke et al. 2016; Dwyer 2004; Kalleberg and Mastekaasa 2001). Third, we use longitudinal data to shift the focus away from comparing movers to non-movers, and instead focus on the effects of moving (Reichelt and Abraham 2017; Cha 2014; Caparrós Ruiz, Lucía Navarro Gómez, and Federico Rueda Narváez 2004).
We offer two findings. First, voluntary mobility is common; quits and promotions are equally likely and are the dominant form of mobility among the core. Second, internal and external mobility are distinctly different mechanisms for improving outcomes. Internal mobility has the strongest effect on earnings growth, while external mobility has the strongest effect on job-fit. Crucially, there is no evidence that quits are a substitute for promotions. Instead, British workers may be using external mobility to better match their skills to their working environment and conditions, in an unpredictable market where they are responsible for skill matching themselves. 
We structure the article as follows; first we summarise the theoretical literature, and introduce a key assumption. Second, we summarise the empirical works and present three hypotheses. Third, we outlines the methodology and approach; fourth, we present the results. A brief discussion concludes.

******************************
Job mobility is an important concept in earnings inequality research. This is especially true in sociology, where differences in *life-chances* are often used to explain inequality [@le2002job; @kalleberg1979sociology; @sorensen1975structure]. If sociologists see outcomes as tied to positions in a structure, voluntary mobility from one job to another should improve a worker's earnings and conditions [@kalleberg2001satisfied; @le2002job]. This assumption forms the basis of the *life-chances approach*, widely used in labour market inequality research [@golsch2006men; @mills2006globalization; @blossfeld2006globalization].

Despite the assumption above, empirical papers routinely fail to find job mobility premiums for movers. Instead, it seems mobility type [@cha2014job], the institutional setting [@pavlopoulos2007benefits], and worker characteristics  [@gesthuizen2009job] play a part in determining mobility premiums. If the majority of workers cannot gain financially from quits or promotions, what do they get from mobility? The view that mobility leads workers to "better" positions may be ignoring a process where workers must bargain and compromise through changing employers (quitting), or changing responsibility with the same employer (taking a promotion). 

The topic of job mobility is underdeveloped in two ways. First, sociology has tended to focus on mobility chances, ignoring the rewards and motivations tied to mobility [@hachen1990three; @hachen1992industrial]. Second, when exploring the consequences of mobility, authors limit studies to external mobility alone [@kronberg2013stay; @kronberg2014stay]. 

This paper agrees with more recent authors, who have moved away from comparing mobile and non-mobile workers [@reichelt2017occupational; @cha2014job], but brings internal careers back into the discussion of mobility. Internal labour markets are still pursued by the majority of workers in the UK and elsewhere [@jacoby1999career]. If they are in decline, can external mobility types replace the rewards offered by promotion [@cappelli1999career]? Putting the question another way, have the benefits of "exit" replaced the benefits of "loyalty" [@hirschman19820]?

This article explores the effects of mobility in the short term, measuring these on subjective and objective outcomes. It shows the consequences of internal mobility differ significantly from external mobility, suggesting both are separate mechanisms. The findings challenge assumptions in the *life-chances approach* which treats both mobilities as movements to “better jobs” \footnote{Internal labour market theory is an exception; however contemporary authors claim these movement types are in decline.}. Instead, internal mobility yields the “attainment” described by earlier works [@sorensen1975structure; @kalleberg1979sociology], while external mobility resembles a need to improve subjective outcomes. The findings contribute to a wider literature on labour market bargaining, where workers trade earnings and conditions for better control or autonomy at work [@dwyer2004downward; @gesthuizen2008mismatching]. To view mobility as a mechanism which improves all outcomes, is to see today’s mobile markets as moving workers from “poor” to “better” jobs. This is not always the case.

The analysis uses job history files from the British Household Panel Survey to compare and contrast quits against promotions. The reasons for choosing the British case are the quality of the longitudinal data (which measures quits and promotions explicitly) and the commonality of mobility in the labour market. Our analysis offers three distinct strengths. First, we consider explicit measures of internal and external mobility; where previous authors have had to operationalise such measures [@kalleberg2001satisfied]. Second, we explore outcomes other than objective pay. By including subjective outcomes the article shows trade-offs made by workers who change jobs within and between employers [@kalleberg2001satisfied; @dwyer2004downward]. Third, we use longitudinal data, exploring the effects of moving positions rather than comparing movers to non-movers. 

Three distinct findings are also offered. First, mobility in the UK is common; the majority of this mobility is “voluntary”. Second, mobility does not affect outcomes evenly; moving positions means compromising between subjective and objective outcomes. Lastly, linked to the previous point, internal and external mobility are separate mechanisms with separate effects on outcomes. Internal mobility has the strongest effect on earnings growth, while external mobility improves satisfaction with work. Results suggest quits and promotions are distinctly different strategies, where promotions lead to attainment [@sorensen1975structure], and quits lead to bargains over working conditions and job match. Crucially, there is no evidence that promotions and quits have the same impact on working conditions and earnings growth. Instead, British workers may be using external mobility as a release valve for poor conditions. In this way, "exit strategies" improve feelings about work; while "loyalty strategies" move workers' careers forward [@hirschman19820].

The article is structured as follows; section one summarises the theoretical literature, and introduces a framework. Section two summarises the empirical work on external and internal mobility, and their relationship to outcomes. Section three presents the methodology and the approach, while section four lists the results. A discussion concludes.
 
# Theoretical Framework

Sociologists often see the labour market as divided into hierarchical structures of positions [@sorensen1975structure; @sorensen1977structure]. These can be tall or flat [@diprete1997collectivist], segmented or porous [@acker2006inequality; @mills2006globalization], and internal or external [@althauser1989internal; @althauser1981firms]. The shape and characteristics of these are widely debated, but such hierarchies are important to understand a market’s inequality. Each position contains its own economic, social, and psychological rewards, specific to that position [@pavlopoulos2007benefits; @sorensen1975structure]. Desirable positions are placed at the upper end of a structure; workers try to reach these over the course of a “career”, or a series of jobs. The best way to reach the top of the structure is by moving between positions, using resources. This is the basis for attainment theory [@sorensen1977structure].

Sociologists have tended to focus on workers’ likelihood of moving through such structures, internally or externally. This approach has informed several important works; career ladders are crucial to firm internal labour markets [@althauser1981firms]; professional credentials are a key step in the entry to protected markets [@freidson1994professionalism]; worker flows from small firms to larger firms are the basis of the dual economy [@averitt1987dual]. Each of these theories implicitly or explicitly discusses the likelihood of job mobility to a new position. Worker differences in mobility patterns are also informed by the approach. Acker’s [-@acker2006inequality] theory of inequality regimes shows how men are “groomed” for promotion, while women move laterally; Sørensen’s [-@sorensen1975structure] work on occupational attainment shows differences in mobility types between black and white workers; Goldthorpe’s [-@goldthorpe2002globalisation] view of class breaks down to those who move to “service relationships” and “labour contracts”. In each example, mobility, and worker access to mobility, is an essential component of earnings inequality.  

Each of these works has a key assumption; voluntary mobility, of either kind, leads workers to better positions with better pay or conditions. Sørensen [-@sorensen1975structure: p460] suggested *“A person may be assumed to shift jobs voluntarily if he can obtain a better job”*; while Hachen [-@hachen1990three: p 320] claimed *“... in industrial societies, individual attainment... is in large part a function of job changes”*. If rewards are specific to positions in a labour market, only a change in positions can lead to a change in rewards, or *“different people in the same job will obtain the same rewards... the same person will obtain different rewards in different jobs”* [@sorensen1977structure: p967]. Even in discussions of vacancy chain models, voluntary mobility is implied as leading to “better”, or more desirable, positions [@rosenfeld1992job].  

In this view, bargaining and compromising are often ignored. Workers either move to better positions via some vacancy mechanism, or they trade their experience for better positions in a market. Looking at the steady rise in precarity and instability found in most western economies [@cappelli1999career; @osterman2014securing] sociologists may interpret the sharp increase in quits as a rise in the number of “better” positions with new employers. This paper agrees that workers use mobility to find “better” jobs, however, the idea that quits and promotions are similar in how they reward workers is unlikely. Mobility within and between firms may be separate mechanisms rewarding workers for different reasons. This hypothesis emerges from a number of empirical papers, summarised below.

# Voluntary mobility & “Better” Positions

Mobility’s consequences are somewhat understudied [@fuller2008job; @pavlopoulos2007benefits; @le2002job]. However, a group of authors find mixed results between mobility and outcomes depending on the type of mobility, the method of estimation, and the country sampled. Articles can be split into those who focus on external mobility alone, and those who compare and contrast internal and external mobility. Typically, voluntary mobility has positive effects on both subjective and objective outcomes. However, results begin to differ when internal mobility and external mobility are compared separately. A review of the literature finds that internal and external mobility yield different outcomes, suggesting workers must make compromises when moving between positions [@kalleberg2001satisfied; @gesthuizen2008mismatching; @dwyer2004downward]. Part of this effect could be explained by Sørensen's [-@sorensen1975structure] suggestion that *“structures of inequality”* differ within and between firms. However, in this explanation, internal mobility should reward workers less than external mobility, since outcomes vary more between firms than within them. Yet, mobility types seem to have different effects on subjective and objective outcomes, a feature that is not considered by the *“structures of inequality”* approach.

## External mobility

Generally, authors find a positive relationship between external mobility and outcomes. Whether these are subjective [@sallaz2017exit; @kalleberg2001satisfied] or objective [@kronberg2013stay; @kronberg2014stay; @cha2014job; @reichelt2017occupational], workers who quit tend to see a positive change; even when moving to similar positions or occupations [@le2002job]. Workers may also use external mobility to trade outcomes, losing out in certain measures for improvements in others [@sallaz2017exit; @dwyer2004downward].

In terms of pay, workers who quit typically move to better paid positions [@kronberg2014stay; @kronberg2013stay]. The effect is also significant over the long-term, and is increasing for white college educated males [@latzke2016consequences; @kronberg2014stay]. Even when correcting for worker differences (individual heterogeneity, where certain workers are more likely to change jobs than others), "economic" quits lead workers to better paid positions with new employers [@fuller2008job].

Regarding conditions, a slight difference emerges. There is evidence that workers "lose out" in certain outcomes after a quit, in order to benefit in others later. Sallaz [-@sallaz2017exit] found that call centre workers, who held well paying jobs without prospects, often took lower paying positions with better conditions in an effort to leave "dead-end" jobs. Dwyer [-@dwyer2004downward] too argued that downward wage mobility was an explicit strategy to improve conditions with new employers. In Germany, Latzke et al. [-@latzke2016consequences] find that quits lead workers to better working conditions, a premium which has remained stable since the 1980's. However, the effect is largely dependent on German mobility directly to a new employer, indirect mobility has no effect on conditions nor pay [@schmelzer2010consequences]. 

The positive effect of quitting may also be tied to premiums in regional mobility. Workers who change regions to take a similar job with a new employer see higher pay premiums than workers who move voluntarily within the same region [@reichelt2017occupational].

Whether all workers benefit from external mobility is unclear. Regarding gender, a wider debate explores whether gender differences in wage returns to quitting stem from compositional differences in quits (men more likely quit than women) [@fuller2008job; @keith1995wage; @keith1997job], or gender differences in the effect of quitting itself (men gaining more from quits than women) [@cha2014job]. Using US data, Kronberg [-@kronberg2013stay] finds that men see greater earnings growth from external mobility, especially in traditionally "good" jobs (those with insurance, security, and high wages). However, Cha [-@cha2014job] finds the opposite, arguing women without children see higher earnings growth from mobility. Importantly, the effect has disappeared since the economic recession in 2008. Fuller [-@fuller2008job] finds no gender difference in the effect of quitting on earnings growth. Thus, differences between men and women may simply stem from the fact that men are more likely to quit. 

Part of the confusion stems from family obligations. In this way women with and without children differ in more important ways than women and men; especially regarding mobility rewards [@cha2014job; @fuller2008job]. Consistently, women without children move to higher paying positions after a quit when compared to women with children; even when both move for "economic" reasons [@fuller2008job; @keith1995wage]. 

Differences in quits premiums also emerge between education groups, although the effect relies heavily on race. Kronberg [-@kronberg2014stay] finds college-educated white men see an earnings premium after quitting, but white workers without a college education see no such premium. A similar relationship emerges among black men with and without a college education. However, the premium for black men is far smaller than white men.  A similar effect emerges in Germany, where class premiums emerge in the effect of quits [@latzke2016consequences]. Pavlopoulos et al. [-@pavlopoulos2007benefits] make the opposite claim; low wage workers have the most to gain from external mobility, and higher paid workers see no premium from quits. In their models, low paid males (who typically have a lower education) see the highest returns on mobility, when compared to high paid males. 

None of the authors above consider internal mobility or promotions, instead they provide a limited view of "voluntary" mobility. This is likely a limitation of the data. Both Fuller [-@fuller2008job] and Keith and McWilliams [-@keith1995wage] sample young workers from the National Longitudinal Survey of Youth, where mobility is split for family, involuntary, and “other” reasons. None of these categories consider internal or external mobility. In Germany too, certain mobility captured by the German Socio-Economic Panel may be flawed [@kattenbach2014quarter], forcing Reichelt and Abraham [-@reichelt2017occupational]  to use alternative data, and Schmelzer [-@schmelzer2010consequences] to drop internal mobility entirely. In many of the papers above it is not clear if the reference category contains "non-movers", or a mix of those who experience promotion and demotion as well as those who stay in a given position. When internal promotions are included, significant differences emerge.

## Internal and external mobility patterns

The relationship between internal and external mobility is less clear. Different effects emerge when authors compare and contrast quits and promotions against staying with the same employer. In most cases, internal and external mobility yield different effects on outcomes. In some, mobility even leads to negative effects for specific workers [@lup2017something, [@pavlopoulos2007benefits]]. Overall, three contradicting interpretations emerge from the articles. First, internal mobility may offer no premium, while external mobility may move (some) workers to higher paid positions [@sallaz2017exit; @pavlopoulos2007benefits]. Second, internal mobility may offer the best premium, while external mobility may lead to faintly better positions [@le2002job; @kalleberg2001satisfied]. Third, mobility types may be separate strategies, affecting different outcomes and motivated by different mechanisms. Here, external mobility could improve subjective feelings about work, while internal mobility could improve objective outcomes like pay and status [@gesthuizen2008mismatching]. 

In short, the effects of internal and external mobility are not as clear as those presented by Sørensen [@sorensen1975structure]. If workers want to improve their outcomes, which strategy should they pursue, and what is the return to each?

Regarding the first argument, Pavlopoulos et al [-@pavlopoulos2007benefits] analyse panel data from the UK and Germany. Overall, the effects of mobility are extremely weak and appears to favour external mobility. Authors find that German workers benefit most from external mobility to new employers, but British workers benefit somewhat from internal mobility with the same employer. These findings only apply to low-paid workers in both countries, suggesting the most vulnerable benefit from mobility types. Regarding high earners, mobility lead these workers to somewhat lower paid positions, although this is likely the result of bargains over working time, bonuses, and other rewards.  

On the second point, some argue the opposite of the above. Internal career structures and ladders yield higher premiums than quits, leading workers to better positions in terms of pay and conditions [@le2002job; @kalleberg2001satisfied]. In Sweden Le Grand and Tahlin [-@le2002job] find that internal mobility yields significantly stronger earnings growth for workers, and that the effect is "pure", in that it remains even when controlling for occupational mobility of workers. External mobility still has a positive effect on earnings growth, but the effect is weaker than internal mobility. This premium remains even after controlling for heterogeneity and endogeneity between mobility and earnings. Ultimately, the authors show that both mobility types act as distinctly different structures of reward, and that internal career ladders reward workers better than external structures.  Kalleberg and Mastekaasa [-@kalleberg2001satisfied] find a similar effect using a set of subjective outcomes. Both findings suggest internal mobility may contain better premiums than external mobility. However, others show that internal promotions can lead workers to subjectively worse positions, especially women [@lup2017something]. In the UK, women who were promoted to lower and upper level management saw a gradual decline in their subjective satisfaction with work; most likely because they moved to worse positions, where pay was not enough to compensate for changes in conditions and responsibility [@lup2017something].

On the last set of findings, it may be that internal and external mobility are "pushed" by separate mechanisms, with promotions driven by earnings growth, and quits driven by a need to improve working conditions or subjective feelings about work [@gesthuizen2009job; @gesthuizen2008mismatching]. Using a Dutch sample, Gesthuizen and Dagevos [@gesthuien2009job] find that internal mobility has the strongest effect on objective outcomes, which are status and earnings growth, while external mobility has the strongest effect on subjective feelings about work. Even when controlling for individual heterogeneity, internal promotions are driven by pay and attainment, while quits are a mechanism for leaving poor work behind. This view also emerges in the US, where downward earnings mobility is a common strategy to improve working conditions and work-life balance [@dwyer2004downward].

The results above are mixed; but overall, papers challenge the idea that job mobility is a utilitarian process, which brings workers to “better” positions. Several papers capture the concept of bargaining and compromising through mobility, where workers do not move to better jobs but sacrifice some outcomes (like job security or job match) for improvements in others (interesting and higher paid work). Part of the bargain may force workers to choose between two mechanisms, their wider networks, or career ladders inside the firm. With this in mind, we propose three hypotheses:

*Hypothesis 1: Voluntary mobility will improve outcomes*

*Hypothesis 2: Internal mobility and external mobility will yield significantly different effects on outcomes*

*Hypothesis 3: Subjective and objective outcomes will be affected differently by different mobility types*

# Methodology

The approach of the article can be summarised as follows. We merge nine rounds of the BHPS covering the pre-crisis period (2000-2008). The panel contains measures of subjective and objective reward, a number of controls, and measures of voluntary job mobility. We estimate the effect of job mobility on subjective outcomes first, using fixed-effects linear regression. We then compare the estimates for internal and external mobility using an f-test. We carry out the same estimation for objective outcomes, and discuss the results.

## Sample

The British Household Panel Survey is a longitudinal study of UK respondents [@taylor1993british]. The data was collected at the household level between 1991 and 2008, with a focus on detailed work histories, socio-economic measures, and rewards at work. It is routinely used to represent the wider British workforce [@pavlopoulos2007benefits; @lup2017something], and is particularly useful for studies of job mobility since the survey explicitly measures both internal and external mobility types, quits and promotions.

The sample is made up of; observations from respondents missing no more than one wave between 2000 and 2008; observations where respondents are employed at each interview and are not in self-employment, inactivity, or education; observations where respondents have no missing job history information for a given survey year. The final data is a semi-balanced, person-year file, which ignores households and focuses on individual responses. It contains 3,782 respondents and 32,560 person-year observations. Although authors argue that unbalanced panels do not hinder multilevel estimation techniques [@gelman2006data], we use a semi-balanced panel for theoretical reasons, avoiding respondents who fall into and out of unemployment. In this way, the analysis focuses on the core workforce. 

## Variables

Two sets of files contain the variables used for estimation, the individual response files “INDRESP”, and the individual job history files “JOBHIST”. Individual response files focus on the status of a given respondent in a survey year. They contain all outcomes (subjective and objective reward) and all controls. The job history files contain measures of job spell data which can be used to measure job mobility. Job history files take the form of job spells nested in individuals. We consider only the most recent spell in a giver respondent’s work history file. Brief, earlier, spells (lasting less than a year) represent economic turbulence rather than clear transitions to new positions. Although previous authors often control for periods of unemployment between positions, this is not the aim of this article, and so these periods are ignored. We allow respondents to have brief periods of unemployment when changing positions, although these are relatively rare. We discuss each of the measures below. 
 
### Job Mobility

Each job history file contains information on the last 12 months of a respondent’s career. Respondents recount each spell of employment, from their most recent, working backwards. Of those who change spell, it’s possible to discern between internal and external changes (JHSTAT). It is also possible to discern between voluntary and involuntary changes (JHSTPY). Those who list a “promotion” or a move to a “better job” are said to move for voluntary reasons. Those who move due to “dismissal”, “redundancy”, or “temporary contracts” are said to move for involuntary reasons. The purpose of the article is to estimate the effect of voluntary mobility, but we argue that controlling for involuntary events is important, since these likely impact outcomes [@keith1995wage; @srensen1975structure]. Respondents who change positions for “other” reasons are controlled for in a category marked “other”; these estimates are not relevant to the analysis and are ignored. 

### Outcomes

Previous studies estimating the consequences of mobility typically focus on pay. While we include the measure here (paygu), the literature notes *“jobs may be characterized by the economic, social and psychological rewards they provide incumbents”* [@sorensen1977structure p967]. With this in mind, focusing on economic consequences alone would offer an incomplete picture of mobility. We consider three subjective outcomes related to pay, hours, and the work itself (jobsat2, jobsat6, and jobsat7). Beyond this, we consider the impact of mobility on weekly working hours, which have been cited as important in more recent works [@sallaz2017exit].

### Controls

Measuring the impact of mobility alone would not give its true effect, especially since fixed-effects regression is vulnerable to omitted-variable bias [@longhi2014practical]. Hence, we include a standard set of controls. Factors like education and gender cannot be included since these are time invariant throughout a person's time in the panel [@longhi2014practical; @wooldridge2015introductory]. However, factors like industry and occupation can be included and would offer a "pure" effect for mobility, in that workers would move to similar positions [@le2002job]. Age and the number of children in the home are also standard controls which commonly explain earnings inequality [@cha2014job; @fuller2008job; @keith1995wage]. Contract type, and the size of the firm are also said to impact differences in earnings [@schmelzer2010consequences]. Lastly, the survey year, the country’s unemployment rate, and the rate of economic growth are included in an effort to control for macro changes which may affect wages and subjective evaluations of work. 

## Estimation

Since voluntary job mobility is not a random event, we control for worker differences by using fixed effects linear estimation. Part of the reason several articles report strong and significant estimates between mobility and outcomes, may be due to differences between mobile and immobile workers (individual heterogeneity). Fixed-effects linear estimation allows us to control for these differences [@allison2009fixed; @longhi2014practical]. 

The method removes all unobserved individual heterogeneity from model’s estimates by subtracting each term from its cluster mean. Wooldridge [-@wooldridge2015introductory p485] refers to this process as *“time demeaning...any explanatory variable that is constant over time for all [individuals] gets swept away by the fixed effects transformation”*. In this approach, all time invariant measures, both observed and unobserved, are dropped from the estimates. The method is particularly suited to Sørensen [-@sorensen1977structure] who argues worker resources are fixed from the moment they enter the labour market. Thus, the change in outcomes resulting from mobility is the effect of respondents “closing the gap” between resources and attainment.

Two limitations should be noted. First, fixed-effects modelling techniques provide unbiased estimates for mobility. However, the method is inefficient and relies on variance within clusters alone, discarding between cluster differences [@allison2009fixed; @longhi2014practical]. Fixed-effects estimates produce larger standard errors, wider confidence intervals, and larger p-values. In response, we treat estimates with p-values of less than 0.1 as statistically significant. Second, fixed effects estimates are susceptible to omitted variable bias. If models omit important measures tied to an outcome, other measures which correlate with the effect will produce significant results. The models below already consider a wide range of explanations for inequality in outcomes, including changes in the occupation and industry of respondents. On average, the models are more conservative than those of other, similar authors. 

# Results

Table 1 lists the frequency of mobility considered overall, between, and within respondents. Most of the UK’s movement is “voluntary”, either to a new employer, or to a new positions with the same employer (column 1). Regarding variation within respondents (column 2), 33% of those sampled changed employers voluntarily at least once; while 30% took internal promotions at least once. 

Involuntary mobility is less common, only 11% of workers experienced involuntary mobility to a new employer, and only 2% changed position involuntarily with the same employer. It should be noted, the sample does not fairly represent involuntary mobility. Since we focus on the core workforce alone, it is likely that we under-estimate the experiences of involuntary mobility in the market. 

Lastly, voluntary mobility has a longer average period than any other mobility type (column 3). For the average worker, both types of voluntary mobility are more common over the 9 wave period than other mobility types. Together, the figures suggest many British workers move often for voluntary reasons.

[TABLE 1 HERE]

## Mobility and subjective outcomes

Mobility is prevalent, but what do workers get from it? The results of three fixed-effects regression models are listed below. They consider the subjective benefits of moving to new positions; satisfaction with work (1), satisfaction with pay (2), and satisfaction with hours (3). For clarity, we omit the estimates for “other” mobility types, which are controlled for, but are irrelevant to the argument.

[TABLE 2 HERE]

Voluntary mobility immediately stands out in the models above; these changes lead workers to better positions. The finding is consistent with Sørensen’s [-@sorensen1977structure; -@sorensen1975structure] predictions. We confirm hypothesis 1. However, internal and external mobility types differ in their effects. These results are not consistent with the attainment approach. 

Considering satisfaction with work (model 1), both types of voluntary mobility lead workers to subjectively better positions, but mobility between firms has a stronger effect than mobility within a firm (F(1, 3723)= 25.54, p >F = 0.000). Workers who leave an employer find better positions than those who take a promotion with the same employer. 

A similar result emerges for satisfaction with pay (model 2), voluntary mobility leads workers to subjectively better positions; however, the effect is larger between firms than within them (F(1, 3723) = 18.21, p > F = 0.000). Again, respondents who leave an employer find more satisfying positions than respondents who take promotions. 

Lastly, satisfaction with time (model 3) is affected in the same way as the previous outcomes. Both types of voluntary mobility lead workers to better positions, but again, respondents who quit an employer see a larger effect, than respondents who take a promotion (F(1, 3723) = 10.32, p > F= 0.001). This too suggests that quitting has a stronger effect on subjective outcomes, than taking a promotion with the same employer.

In each case, those who leave an employer move to more satisfying positions than those who use internal career ladders. In this sense, voluntary mobility may be driven by two separate mechanisms, internal structures on one hand, and the wider market on the other. Using the findings above, we confirm hypothesis 2; internal and external mobility have significantly different effects on outcomes. 

It may be that external mobility is driven by job-mismatch instead of attainment as described in the literature. Workers who quit a firm may be less interested in career progression, and more interested in leaving behind poor conditions for better ones.

Before committing to the explanation, it’s worth considering an alternative. It’s possible the effect stems from working conditions varying more between firms than within them. Sørensen [-@sorensen1977structure] suggests this implicitly, claiming that *“opportunity structures”* dictate the extent to which workers can close the gap between their rewards and their resources. These may be narrower in firms, than the wider market, leading to smaller mobility effects. Putting the issue another way, a firm is limited in how much conditions can vary within the organisation in a way that the market is not. If such opportunity structures exist, a set of objective outcomes will respond to mobility in the same way as above; with external mobility yielding strong effects, and internal mobility yielding weaker effects. We consider the idea below, while revisiting hypotheses 1 and 2.

## Mobility and objective outcomes

The models in Table 3 are similar to those in Table 2, but estimate the effect of mobility on weekly hours worked (1) and log wages (2). Since mobility has a significant effect on both outcomes, we consider the model for wages a second time, while controlling for weekly hours worked. The results vary drastically from the previous estimates, and suggest internal mobility has the strongest effect for workers' pay.  

[TABLE 3 HERE]

The effects of voluntary mobility are less clear than before. Voluntary change appears to have an effect on hours and pay, but only under certain conditions. Internal mobility has the largest premiums on pay without the corresponding rise in hours. External mobility leads workers to positions with higher pay and longer hours. While one mobility type resembles the attainment described by Sørensen [@sorensen1975structure], the other resembles negotiations over working time, as a strategy to increase pay.

Starting with weekly working hours; voluntary mobility has a mixed effect on hours. External mobility leads workers to positions with longer hours (model 1), and internal mobility leads workers to positions with fewer hours. However, the effect for internal mobility is insignificant. Changing employers voluntarily may be the product of searching for longer hours, or moving from a part-time position, to a more full-time position.   

Considering gross monthly pay (model 2), voluntary mobility has only a minor effect. Those who change positions voluntarily (within or between firms) gain a 1% increase in gross monthly pay. There is no difference between internal and external mobility. Although an increase in pay exists, workers may need to pursue several new positions over the course of a career before seeing a substantial earnings growth. Still, a mechanism for understanding earnings inequality exists in the model above. 

Thinking of the two models together, the 1% increase in pay may be tied to workers taking longer hours. This effect does not exist for those who move internally, only external mobility types are affected. With this in mind, we ask what portion of the effect of mobility on pay (model 2) is explained by changes in weekly working time (model 1). Re-estimating gross pay while controlling for hours (model 3) eliminates the positive effect for external voluntary mobility, *but not internal voluntary mobility*. Thus external mobility is tied to bargains over hours for similar rates of pay; while internal mobility is tied to earnings growth, in itself. From the estimates above, we reject hypothesis 1. Voluntary mobility, in itself, does not improve objective outcomes, and relies heavily on the type of mobility pursued. However, we accept hypothesis 2; internal and external mobility yields different effects on the same outcome. 

The estimates in Table 3 cast doubt over the previous findings. Voluntary mobility alone does not have a positive effect on all outcomes. In fact, there are differences between internal and external mobility when it comes to pay and weekly working hours. Further, these differences are the exact opposite of those in Table 2. External mobility is a strategy which increases pay through increased hours, while internal mobility increases the rate of pay, leading to earnings growth. Respondents who quit work for a new employer appear move to similarly paid positions, with longer working hours. Respondents who take promotions experience the attainment described by Sørensen [@sorensen1977structure]. For this reason, we accept hypothesis 3. Internal and external mobility, affect outcome type differently.  

# Discussion

The idea that workers move to better positions when voluntarily changing jobs, does not emerge, as with several authors discussed in the review above [@sallaz2017exit; @pavlopoulos2007benefit; @kalleberg2001satisfied]. Neither does the idea that opportunity structures provide large or small premiums within and between firms [@sorensen1978labor]. Instead internal and external mobility are distinctly different mechanisms, with different forms of bargaining. Despite authors citing the death of internal labour markets, it seems that the reward systems found in internal structures do not appear in external structures [@cappelli1999career; @jacoby1999career]. Authors who call for a nuanced approach to the study of job mobility should focus on the importance of internal mobility within the firm, which still rewards workers significantly [@reichelt@2017occupation; @latzke216consequences].

The results do not refute that job mobility is important in understanding earnings inequality, rather they suggest that workers are pursuing two separate strategies for dealing with inequality in the British labour market. On one hand, workers who want to improve conditions leave an employer for better positions, even if it means working longer hours. On the other, workers who want higher earnings must use a firm's internal structures to improve their worth. Understanding earnings inequality may rely on better understanding who it is who is promoted, and who it is who takes positions with the possibility of seeing promotion. 

Attainment theory proposed by Sørensen [@sorensen1975structure; @sorensen1977structure; @sorensen1978labor] fails to account for two findings, although some are noted by efficiency wage theorists elsewhere [@akerlof1986efficiency] and internal labour market theory [@althauser1989internal; @althauser1981firms]. First, there is a distinct difference between internal and external mobility in terms of their effects on outcomes. External mobility improves subjective outcomes best, while internal mobility improves actual pay without increasing hours. Second, tied to the first point, there is a clear difference between mobility’s effect on subjective and objective outcomes. Attainment theory expects “psychological” rewards to work in the same way as “economic” rewards. The theory of attainment cannot account for mobility driven by precarity and mismatch, where workers try to adjust for poor working conditions for similar rates of pay. From the output, it seems job-mismatch drives external mobility as workers search for better conditions and an internal structure to commit to, one that may eventually offer attainment or progress in the form of internal promotion.

The suggestion that workers should embrace economic turbulence, and multi-employer careers in general, should be treated with skepticism; at least in the UK [@brown2008economic; @oecd2010oecd]. This suggestion conflates the interests of employers and the interests of workers as the same. Workers may use external mobility to find firm internal labour markets to commit to, which will eventually grant them the chance to climb a career ladder. However, this is not the promise offered by advocates of mobile labour markets. Generally, sociologists should continue asking what workers get out of mobility.






# Bibliography
